pysimplelife/core/urls.py
from django.conf.urls import url
from django.contrib.auth import views as django_auth_views
from django.urls import reverse_lazy

from . import views

app_name = 'core'


urlpatterns = [
    url(r'^register/$', views.UserRegistrationView.as_view(), name='register'),
    url(r'^login/$', django_auth_views.LoginView.as_view(template_name='core/login.html',
           redirect_authenticated_user=True), name='login'),
    url(r'^logout/$', django_auth_views.LogoutView.as_view(), name='logout'),
    url(r'^password_reset/$', django_auth_views.PasswordResetView.as_view(template_name='core/password_reset.html',
            email_template_name='core/password_reset_email.html', success_url=reverse_lazy('core:password_reset_done')),
            name='password_reset'),
    url(r'^password_reset_done/$', django_auth_views.PasswordResetDoneView.as_view(template_name='core/password_reset_done.html'),
            name='password_reset_done'),
    url(r'^password_reset_confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
            django_auth_views.PasswordResetConfirmView.as_view(template_name='core/password_reset_confirm.html',
            success_url=reverse_lazy('core:password_reset_complete')), name='password_reset_confirm'),
    url(r'^password_reset_complete/$', django_auth_views.PasswordResetCompleteView.as_view(template_name='core/password_reset_complete.html'),
            name='password_reset_complete'),
    url(r'^email_verification_required/$', views.EmailVerificationRequiredView.as_view(),
            name='email_verification_required'),
    url(r'^email_verify/(?P<user_id>\d+)/(?P<verification_code>[0-9A-Fa-f-]+)', views.EmailVerifyView.as_view(), name='email_verify'),
    # Dummy url to enable reversing without arguments
    url(r'^email_verify/', views.EmailVerifyView.as_view(), name='email_verify_dummy'),
    url(r'^login_redirect/$', views.LoginRedirectView.as_view(), name='login_redirect'),
    url(r'^password_change/$', django_auth_views.PasswordChangeView.as_view(template_name='core/password_change.html',
            success_url=reverse_lazy('core:password_change_done')),
            name='password_change'),
    url(r'^password_change_done/$', django_auth_views.PasswordChangeDoneView.as_view(template_name='core/password_change_done.html'),
            name='password_change_done'),
]

pysimplelife/pyadmin/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView

from . import views


urlpatterns = [
    url(r'^home/$', views.Page1TemplateView.as_view(), name='index'),
    url(r'^settings/$', views.settings, name='settings'),
    url(r'^app2/$', views.Page2TemplateView.as_view(), name='app2'),
    url(r'^app3/$', views.Page3TemplateView.as_view(), name='app3'),
    url(r'^app4/$', views.Page4TemplateView.as_view(), name='app4'),
    url(r'^app5/$', views.Page5TemplateView.as_view(), name='app5'),
    url(r'^app6/$', views.Page6TemplateView.as_view(), name='app6'),
    url(r'^app7/$', views.Page7TemplateView.as_view(), name='app7'),
]

pysimplelife/pysimplelife/urls.py
from django.conf.urls import include, url
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin


urlpatterns = [
    url(r'^oauth/', include('social_django.urls', namespace='social')),  # <-- For OAuth
    url(r'^admin/', admin.site.urls),
    url(r'^', include('core.urls', namespace='core')),
    url(r'^', include('pyadmin.urls', namespace='pyadmin')),
    url(r'^', include('public.urls', namespace='public')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pysimplelife/templates/base.html
{% load staticfiles %}
{% load crispy_forms_tags %}

<!DOCTYPE html>
<html lang="en">

<head>
    {% include 'head_meta.html' %}
    <title>{% block title %}Pysimplelife - Home{% endblock %}</title>
    {% include 'head_css.html' %}
</head>

<body>
    <div id="wrapper">
        <!-- Navigation -->
        {% include 'nav_page.html' %}
        <div id="page-wrapper">
            {% block content %}
            {% endblock %}
        </div>
        <!-- /#page-wrapper -->
    </div>
    <!-- /#wrapper -->
    {% include 'javascript_foot.html' %}
</body>

</html>

pysimplelife/templates/head_css.html
{% load static %}
{% load crispy_forms_tags %}

    <link href="{% static 'admin/css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'admin/css/sb-admin.css' %}" rel="stylesheet">
    <link href="{% static 'admin/css/plugins/morris.css' %}" rel="stylesheet">
    <link href="{% static 'admin/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">
    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
    <style>
        .navbar-inverse {
            background-color: darkslategray !important;
            border-color: darkslategray !important;
        }
        .navbar-inverse .navbar-toggle {
             border-color: antiquewhite;
        }
        .collapse {
            background-color: darkslategray !important;
            border-color: darkslategray !important;
            color: antiquewhite;
        }
        .side-nav>li>ul>a:hover {
            color: antiquewhite !important;
            background-color: darkslategray !important;
         }
        .navbar-toggle>a:hover {
            color: #1b6d85;
            background-color: #1b6d85;
        }
        .navbar-inverse .navbar-nav>li>a {
            color: antiquewhite !important;
        }
        .side-nav>li>ul>li>a {
            display: block;
            padding: 10px 15px 10px 38px;
            text-decoration: none;
            color: antiquewhite;
            background-color: darkslategray;
        }
        .navbar-inverse .navbar-nav>li>a {
            color: antiquewhite; !important;
        }
        .navbar-inverse .navbar-nav>li>a:hover {
            background-color: #1b6d85; !important;
        }
        .navbar-inverse .navbar-nav>li>a>li>a:hover {
            background-color: #1b6d85; !important;
        }
    </style>

pysimplelife/templates/head_meta.html

<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="description" content="@pyprogrammer88">
<meta name="author" content="@pyprogrammer88">

pysimplelife/templates/javascript_foot.html
{% load static %}
{% load crispy_forms_tags %}
    <script src="{% static 'admin/js/jquery.js' %}"></script>
    <script src="{% static 'admin/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/raphael.min.js' %}"></script>
    <script src="{% static 'js/morris.min.js' %}"></script>
    <script src="{% static 'js/morris-data.js' %}"></script>

pysimplelife/templates/nav_page.html
{% load static %}
{% load crispy_forms_tags %}

<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" style="" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
                    <span class="sr-only" style="color: antiquewhite">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{% url 'core:login_redirect' %}" style="color: antiquewhite"><strong>PySimplelife</strong></a>
            </div>
            <!-- Top Menu Items -->
            <ul class="nav navbar-right top-nav">
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-envelope"></i> <b class="caret"></b></a>
                    <ul class="dropdown-menu message-dropdown">
                        <li class="message-preview">
                            <a href="#">
                                <div class="media">
                                    <span class="pull-left">
                                        <img class="media-object" src="http://placehold.it/50x50" alt="">
                                    </span>
                                    <div class="media-body">
                                        <h5 class="media-heading"><strong>{{ request.user }}</strong>
                                        </h5>
                                        <p class="small text-muted"><i class="fa fa-clock-o"></i> Yesterday at 4:32 PM</p>
                                        <p>Lorem ipsum dolor sit amet, consectetur...</p>
                                    </div>
                                </div>
                            </a>
                        </li>
                        <li class="message-preview">
                            <a href="#">
                                <div class="media">
                                    <span class="pull-left">
                                        <img class="media-object" src="http://placehold.it/50x50" alt="">
                                    </span>
                                    <div class="media-body">
                                        <h5 class="media-heading"><strong>{{ request.user }}</strong>
                                        </h5>
                                        <p class="small text-muted"><i class="fa fa-clock-o"></i> Yesterday at 4:32 PM</p>
                                        <p>Lorem ipsum dolor sit amet, consectetur...</p>
                                    </div>
                                </div>
                            </a>
                        </li>
                        <li class="message-preview">
                            <a href="#">
                                <div class="media">
                                    <span class="pull-left">
                                        <img class="media-object" src="http://placehold.it/50x50" alt="">
                                    </span>
                                    <div class="media-body">
                                        <h5 class="media-heading"><strong>{{ request.user }}</strong>
                                        </h5>
                                        <p class="small text-muted"><i class="fa fa-clock-o"></i> Yesterday at 4:32 PM</p>
                                        <p>Lorem ipsum dolor sit amet, consectetur...</p>
                                    </div>
                                </div>
                            </a>
                        </li>
                        <li class="message-footer">
                            <a href="#">Read All New Messages</a>
                        </li>
                    </ul>
                </li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-bell"></i> <b class="caret"></b></a>
                    <ul class="dropdown-menu alert-dropdown">
                        <li>
                            <a href="#">Alert Name <span class="label label-default">Alert Badge</span></a>
                        </li>
                        <li>
                            <a href="#">Alert Name <span class="label label-primary">Alert Badge</span></a>
                        </li>
                        <li>
                            <a href="#">Alert Name <span class="label label-success">Alert Badge</span></a>
                        </li>
                        <li>
                            <a href="#">Alert Name <span class="label label-info">Alert Badge</span></a>
                        </li>
                        <li>
                            <a href="#">Alert Name <span class="label label-warning">Alert Badge</span></a>
                        </li>
                        <li>
                            <a href="#">Alert Name <span class="label label-danger">Alert Badge</span></a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="#">View All</a>
                        </li>
                    </ul>
                </li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user"></i> {{ request.user }} <b class="caret"></b></a>
                    <ul class="dropdown-menu">
                        <li>
                            <a href="#"><i class="fa fa-fw fa-user"></i> Profile</a>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-fw fa-envelope"></i> Inbox</a>
                        </li>
                        <li>
                            <a href="#"><i class="fa fa-fw fa-gear"></i> Settings</a>
                        </li>
                        <li class="divider"></li>
                        <li>
                            <a href="{% url 'core:logout' %}"><i class="fa fa-fw fa-power-off"></i> Log Out</a>
                        </li>
                    </ul>
                </li>
            </ul>
            <!-- Sidebar Menu Items - These collapse to the responsive navigation menu on small screens -->
            <div class="collapse navbar-collapse navbar-ex1-collapse">
                <ul class="nav navbar-nav side-nav">
                    <li style="color: antiquewhite;">
                        <a href="{% url 'pyadmin:index' %}"><i class="fa fa-fw fa-dashboard" style="color: antiquewhite"></i> Dashboard</a>
                    </li>
                    <li>
                        <a href="{% url 'pyadmin:index' %}"><i class="fa fa-fw fa-bar-chart-o" style="color: antiquewhite"></i> Charts</a>
                    </li>
                    <li>
                        <a href="{% url 'pyadmin:app2' %}"><i class="fa fa-fw fa-table" style="color: antiquewhite"></i> Tables</a>
                    </li>
                    <li>
                        <a href="{% url 'pyadmin:app3' %}"><i class="fa fa-fw fa-edit" style="color: antiquewhite"></i> Forms</a>
                    </li>
                    <li>
                        <a href="{% url 'pyadmin:app4' %}"><i class="fa fa-fw fa-desktop" style="color: antiquewhite"></i> Bootstrap Elements</a>
                    </li>
                    <li>
                        <a href="{% url 'pyadmin:app5' %}"><i class="fa fa-fw fa-wrench" style="color: antiquewhite"></i> Bootstrap Grid</a>
                    </li>
                    <li>
                        <a href="javascript:;" data-toggle="collapse" data-target="#demo"><i class="fa fa-fw fa-arrows-v" style="color: antiquewhite"></i> Dropdown <i class="fa fa-fw fa-caret-down"></i></a>
                        <ul id="demo" class="collapse">
                            <li>
                                <a href="#">Dropdown Item</a>
                            </li>
                            <li>
                                <a href="#">Dropdown Item</a>
                            </li>
                        </ul>
                    </li>
                    <li>
                        <a href="{% url 'pyadmin:app6' %}"><i class="fa fa-fw fa-file" style="color: antiquewhite"></i> Blank Page</a>
                    </li>
                    <li>
                        <a href="{% url 'pyadmin:app7' %}"><i class="fa fa-fw fa-dashboard" style="color: antiquewhite"></i> RTL Dashboard</a>
                    </li>
                </ul>
            </div>
            <!-- /.navbar-collapse -->
        </nav>