pysimplelife/core/urls.py
from django.conf.urls import url
from django.contrib.auth import views as django_auth_views
from django.urls import reverse_lazy

from . import views

app_name = 'core'


urlpatterns = [
    url(r'^register/$', views.UserRegistrationView.as_view(), name='register'),
    url(r'^login/$', django_auth_views.LoginView.as_view(template_name='core/login.html',
           redirect_authenticated_user=True), name='login'),
    url(r'^logout/$', django_auth_views.LogoutView.as_view(), name='logout'),
    url(r'^password_reset/$', django_auth_views.PasswordResetView.as_view(template_name='core/password_reset.html',
            email_template_name='core/password_reset_email.html', success_url=reverse_lazy('core:password_reset_done')),
            name='password_reset'),
    url(r'^password_reset_done/$', django_auth_views.PasswordResetDoneView.as_view(template_name='core/password_reset_done.html'),
            name='password_reset_done'),
    url(r'^password_reset_confirm/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
            django_auth_views.PasswordResetConfirmView.as_view(template_name='core/password_reset_confirm.html',
            success_url=reverse_lazy('core:password_reset_complete')), name='password_reset_confirm'),
    url(r'^password_reset_complete/$', django_auth_views.PasswordResetCompleteView.as_view(template_name='core/password_reset_complete.html'),
            name='password_reset_complete'),
    url(r'^email_verification_required/$', views.EmailVerificationRequiredView.as_view(),
            name='email_verification_required'),
    url(r'^email_verify/(?P<user_id>\d+)/(?P<verification_code>[0-9A-Fa-f-]+)', views.EmailVerifyView.as_view(), name='email_verify'),
    # Dummy url to enable reversing without arguments
    url(r'^email_verify/', views.EmailVerifyView.as_view(), name='email_verify_dummy'),
    url(r'^login_redirect/$', views.LoginRedirectView.as_view(), name='login_redirect'),
    url(r'^password_change/$', django_auth_views.PasswordChangeView.as_view(template_name='core/password_change.html',
            success_url=reverse_lazy('core:password_change_done')),
            name='password_change'),
    url(r'^password_change_done/$', django_auth_views.PasswordChangeDoneView.as_view(template_name='core/password_change_done.html'),
            name='password_change_done'),
]

pysimplelife/pysimplelife/urls.py
from django.conf.urls import include, url
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin


urlpatterns = [
    url(r'^oauth/', include('social_django.urls', namespace='social')),  # <-- For OAuth
    url(r'^admin/', admin.site.urls),
    url(r'^', include('core.urls', namespace='core')),
    url(r'^', include('pyadmin.urls', namespace='pyadmin')),
    url(r'^', include('public.urls', namespace='public')),
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pysimplelife/core/models.py
import uuid

from django.contrib.auth.models import AbstractBaseUser, PermissionsMixin, BaseUserManager, Group
from django.db import models
from django.shortcuts import redirect
from django.core.validators import validate_email
from django.urls import reverse_lazy
from django.core.mail import send_mail
from django.conf import settings


class UserManager(BaseUserManager):
    """
    This model remake Django's built-in User model in order to login with email.
    """

    def create_user(self, email, password=None, first_name=None, last_name=None, **extra_fields):
        if not email:
            raise ValueError('Enter an email address')
        if not first_name:
            raise ValueError('Enter a first name')
        if not last_name:
            raise ValueError('Enter a last name')
        email = self.normalize_email(email)
        user = self.model(email=email, first_name=first_name, last_name=last_name, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password=None, first_name=None, last_name=None, **extra_fields):
        user = self.create_user(email=email, password=password, first_name=first_name, last_name=last_name)
        user.is_superuser = True
        user.is_staff = True
        user.save(using=self._db)
        return user


class User(AbstractBaseUser, PermissionsMixin):

    # Verification fields
    email = models.EmailField('Email', unique=True, validators=[validate_email])
    first_name = models.CharField('First Name', max_length=50)
    last_name = models.CharField('Last Name', max_length=50)
    date_joined = models.DateTimeField(auto_now_add=True)
    is_active = models.BooleanField('is active', default=True)
    is_staff = models.BooleanField('is staff', default=False)

    # Verification fields
    email_verified = models.BooleanField(default=False)
    email_verification_code = models.UUIDField(default=uuid.uuid4, null=True)

    # Other fields
    updated = models.DateTimeField('updated', auto_now=True)

    objects = UserManager()
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ('first_name', 'last_name')

    def __str__(self):
        return '{} {}'.format(self.first_name, self.last_name)

    def get_absolute_url(self):
        #return reverse('users:profile', args=[self.pk])
        return redirect('/')

    class Meta:
        default_permissions = ['manage']
        ordering = ('first_name',)

    def get_full_name(self):
        return '{} {}'.format(self.first_name, self.last_name)

    def get_short_name(self):
        return self.get_full_name()

    def send_email_verification_code(self):
        """
        Sends the user an email with a link to click to verify their email address
        """

        if self.email_verification_code:
            verification_code = self.email_verification_code
        else:
            verification_code = uuid.uuid4()
            self.email_verification_code = verification_code
            self.save()

        context = {
            'link': 'http://127.0.0.1:8000' +
                    str(reverse_lazy('core:email_verify',
                                     kwargs={'user_id': self.id, 'verification_code': verification_code}))
        }
        subject = 'Welcome to PySimplelife.com'
        message = 'In order to finish registration please click in this email -> ' + str(context['link'])
        from_email = settings.EMAIL_HOST_USER
        to_list = [self.email, settings.EMAIL_HOST_USER]
        send_mail(subject, message, from_email, to_list, fail_silently=False)


class GroupSettings(models.Model):
    """
    This model extends Django's built-in Group model with more attributes.
    """

    group = models.OneToOneField(Group, on_delete=models.CASCADE)
    default_manager_group = models.BooleanField(default=False)

    def __str__(self):
        return 'Group {} settings'.format(self.group.name)

    class Meta:
        default_permissions = ['manage']


pysimplelife/core/forms.py
from django.contrib.auth.hashers import check_password
from django.utils import timezone
from django import forms
from django.contrib.auth.forms import UserCreationForm

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit


from .models import User


class UserRegistrationForm(UserCreationForm):
    """
    This form is used to create a new user account.
    """

    email2 = forms.EmailField(required=True, label='Email confirmation')

    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email', 'email2', 'password1', 'password2', ]

    def __init__(self, *args, **kwargs):
        super(UserRegistrationForm, self).__init__(*args, **kwargs)
        self.helper = FormHelper(self)
        self.helper.add_input(Submit('submit', 'Register'))
        #self.fields['email2'].help_text = 'Enter your E-mail again to verify.'

    def clean(self):
        super(UserRegistrationForm, self).clean()

        if self.cleaned_data.get('email') and self.cleaned_data.get('email2'):
            if not self.cleaned_data.get('email') == self.cleaned_data.get('email2'):
                self._errors['email2'] = self.error_class(['There is a mismatch in your E-mail.'])

    def save(self, commit=True):
        user = super(UserRegistrationForm, self).save()
        user.send_email_verification_code()
        return user


class ConfirmationPasswordForm(forms.ModelForm):
    """
    This form is used to check if user is active.
    """

    confirm_password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ['confirm_password', ]

    def clean(self):
        super(ConfirmationPasswordForm, self).clean()

        confirm_password = self.cleaned_data.get('confirm_password')
        if not check_password(confirm_password, self.instance.password):
            self.add_error('confirm_password', 'Password does not match.')

    def save(self, commit=True):
        user = super(ConfirmationPasswordForm, self).save()
        user.last_login = timezone.now()
        if commit:
            user.save()
        return user

pysimplelife/core/views.py
from django.views.generic import CreateView, TemplateView, View, UpdateView
from django.utils.decorators import method_decorator
from django.contrib.auth.decorators import login_required
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.contrib import messages
from django.shortcuts import redirect, render, get_object_or_404
from django.http import HttpResponseNotFound

from .models import User
from .forms import UserRegistrationForm
from .forms import ConfirmationPasswordForm
from .mixins import LoginRequiredMixin



class UserRegistrationView(SuccessMessageMixin, CreateView):
    """
    This class is used for user registration
    """

    model = User
    form_class = UserRegistrationForm
    template_name = 'core/register.html'

    success_message = 'Your account has been created and you can now log in. Check your email for a message ' \
                      'about confirming your email address.'
    success_url = reverse_lazy('core:login')


class EmailVerifyView(View):
    """
    This class change verified true by clicking
    """

    def get(self, request, *args, **kwargs):
        if not self.kwargs.get('user_id') or not self.kwargs.get('verification_code'):
            return HttpResponseNotFound

        user = get_object_or_404(User, pk=self.kwargs['user_id'],
                                 email_verification_code=self.kwargs['verification_code'])
        user.email_verified = True
        # user.email_verification_code = None
        user.save()
        return render(request, 'core/email_verification.html')


class EmailVerificationRequiredView(LoginRequiredMixin, TemplateView):
    """
    EmailVerificationRequiredMiddleware redirects the user to this view as long as their email address is not verified.
    """

    template_name = 'core/email_verification_required.html'


class LoginRedirectView(LoginRequiredMixin, View):
    """
    This view determines where to send the user after logging in. If the user is a pharmacist or a manager they will
    be sent to those sections respectively. If the user is a patient but does not have any coupled patients, the user
    is redirected to coupling their first patient. If the user is a patient and has at least one coupled patient they
    will be sent to the patient section.
    """

    def get(self, request, *args, **kwargs):
        if request.user.is_staff:
            return redirect(reverse_lazy('pyadmin:index'))
        elif request.user.is_authenticated:
            return redirect(reverse_lazy('pyadmin:index'))
        else:
            return redirect(reverse_lazy('public:index'))


class ConfirmationPasswordView(UpdateView):

    form_class = ConfirmationPasswordForm
    template_name = 'core/confirmation_password.html'

    def get_object(self, queryset=None):
        return self.request.user

    def get_success_url(self):
        return self.request.get_full_path()

pysimplelife/templates/core/base.html
<!DOCTYPE html>

<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="A simple site to make life easier">
    <meta name="author" content="@PyProgrammer88">
    <link rel="icon" href="../../favicon.ico">

    <title>{% block title %}Pysimplelife | Cover{% endblock %}</title>

    <link href="/static/css/bootstrap.min.css" rel="stylesheet">
    <link href="/static/css/ie10-viewport-bug-workaround.css" rel="stylesheet">
    <link href="/static/css/cover.css" rel="stylesheet">
    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->
    <script src="/static/js/ie-emulation-modes-warning.js"></script>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <div class="site-wrapper">

      <div class="site-wrapper-inner">

        <div class="cover-container">

          <div class="masthead clearfix">
            <div class="inner">
              <h3 class="masthead-brand"></h3>
              <nav>
                <ul class="nav masthead-nav">
                </ul>
              </nav>
            </div>
          </div>

          <div class="inner cover">
            {% block content %}
            {% endblock %}
          </div>

          <div class="mastfoot">
            <div class="inner">
              <p>Pysimplelife.com, by <a href="https://twitter.com/pyprogrammer88">@pyprogrammer88</a>.</p>
            </div>
          </div>

        </div>

      </div>

    </div>

    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script>window.jQuery || document.write('<script src="../../assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src="/static/js/bootstrap.min.js"></script>
    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="/static/js/ie10-viewport-bug-workaround.js"></script>
  </body>
</html>

pysimplelife/templates/core/confirmation_password.html
{% extends 'core/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}Pysimplelife - Login{% endblock title %}

{% block content %}
<h2 class='text-align-center'><strong>Login on Pysimplelife</strong></h2>
  <div class='col-sm-6 col-sm-offset-3'>

    <div class="panel-body">
      <form method="post">
        {{ form|crispy }}
        {% csrf_token %}
        <button type="submit" class='btn btn-block btn-default'><strong>Confirm</strong></button>
      </form>
    </div>
  </div>
{% endblock content %}

pysimplelife/templates/core/email_verification.html
{% extends 'core/base.html' %}

{% block title %}Email confirmation - Pysimplelife{% endblock title %}

{% block content %}
<h2 class='text-align-center'><strong>Confirmed Email</strong></h2>
    <div class="panel-body">
       <h3>Thank you for confirming your email address.</h3>
    <br/>
      {% if request.user.is_authenticated %}
          <p class="lead">
              <a href="{% url 'core:login_redirect' %}" class="btn btn-lg btn-default">Go home</a>
          </p>
      {% else %}
          <p class="lead">
              <a href="{% url 'core:login' %}" class="btn btn-lg btn-default">Login</a>
          </p>
      {% endif %}
    </div>
{% endblock content %}

pysimplelife/templates/core/email_verification_required.html
{% extends 'core/base.html' %}


{% block title %}Email confirm required - Pysimplelife{% endblock title %}

{% block content %}
<h2 class='text-align-center'><strong>Email confirmation required</strong></h2>
    <div class="panel-body">
        <h3>You must confirm your email address before you can enter. You have received an email when you registered.</h3>
        <h3>Click on the link in the email to confirm your email address.</h3>
        <br>
        <h3>If you want receive a link again, please click <a href="{% url 'core:logout' %}">here</a></h3>
    </div>
{% endblock content %}

pysimplelife/templates/core/login.html
{% extends 'core/base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}Pysimplelife - Login{% endblock title %}

{% block content %}
<h2 class='text-align-center'><strong>Login on Pysimplelife</strong></h2>
  <div class='col-sm-6 col-sm-offset-3'>

    <div class="panel-body">
      <form method="post" action=".">
        {{ form|crispy }}
        {% csrf_token %}
        <input type="hidden" name="next" value="{{ next }}" />
        <button type="submit" class='btn btn-block btn-default'><strong>Login</strong></button>
      </form>
    </div>
  </div>
      <br />
       <div class='row'>
        <div class='col-sm-6 col-sm-offset-3'>
            <br/>
            <p><a href="{% url 'core:password_reset' %}">I forgot my password</a></p>
            <p><a href="{% url 'core:register' %}">I do not have an account yet</a></p>
        </div>
       </div>

{% endblock content %}

pysimplelife/templates/core/messages.html
{% for message in messages %}
  <div class="alert {{ message.tags }} alert-dismissible fade" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
    {{ message|safe }}
  </div>
{% endfor %}

pysimplelife/templates/core/no_permission.html
{% extends 'core/base.html' %}


{% block title %}Not acceess - Pysimplelife{% endblock title %}

{% block content %}

<h2 class='text-align-center'><strong>No access</strong></h2>
    <div class="panel-body">
        <h3>You are not authorized to access this page.</h3>
    </div>

{% endblock content %}

pysimplelife/templates/core/paginator.html
<tfoot>
<tr>
  <td><b>Totaal: {{ page_obj.paginator.count }}</b> - {{ page_obj.paginator.per_page }} per pagina</td>
  <td colspan="{{ colspan }}" align="right">
    <span class="step-links">
      {% if page_obj.has_previous %}
        <a href="?page=1"><i class="fa fa-fast-backward"></i></a>
        <a href="?page={{ page_obj.previous_page_number }}"><i class="fa fa-step-backward"></i></a>
      {% endif %}
      <span class="current">
        pagina {{ page_obj.number }} van {{ page_obj.paginator.num_pages }}
      </span>
      {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}"><i class="fa fa-step-forward"></i></a>
        <a href="?page=last"><i class="fa fa-fast-forward"></i></a>
      {% endif %}
    </span>
  </td>
</tr>
</tfoot>

pysimplelife/templates/core/password_change.html
{% extends 'core/base.html' %}
{% load crispy_forms_filters %}

{% block title %}Change password - Pysimplelife{% endblock title %}

{% block content %}
<h2 class='text-align-center'><strong>Change password</strong></h2>
      <form method="post" action=".">
        <p class="tex align-center">Enter your current password for verification and then choose your new password.</p>
        {{ form|crispy }}
        {% csrf_token %}
        <button type="submit" class='btn btn-block btn-default'><strong>Save</strong></button>
      </form>
<br/>
{% endblock content %}

pysimplelife/templates/core/password_change_done.html
{% extends 'core/base.html' %}

{% block title %}Password changed - Pysimplelife{% endblock title %}

{% block content %}

    <h3>Your password has been changed.</h3>

{% endblock content %}

pysimplelife/templates/core/password_reset.html
{% extends 'core/base.html' %}
{% load crispy_forms_filters %}

{% block title %}Forgotten password - Pysimplelife{% endblock title %}

{% block content %}

<h2 class='text-align-center'><strong>Reset password</strong></h2>
  <div class='col-sm-6 col-sm-offset-3'>
    <div class="panel-body">
      <form method="post" action=".">
        <p class="tex align-center">Have you forgotten your password? Fill your Email and an Email will be send to you with instructions.</p>
        {{ form|crispy }}
        {% csrf_token %}
        <button type="submit" class='btn btn-block btn-default'><strong>Send</strong></button>
      </form>
    </div>
  </div>
<br/>

{% endblock content %}

pysimplelife/templates/core/password_reset_confirm.html
{% extends 'core/base.html' %}
{% load crispy_forms_filters %}

{% block title %}Reset Password - Pysimplelife{% endblock title %}

{% block content %}

<h2 class='text-align-center'><strong>Reset password</strong></h2>
  <div class='col-sm-6 col-sm-offset-3'>
    <div class="panel-body">
      <form method="post" action=".">
        <p class="tex align-center">Fill in your new password.</p>
        {{ form|crispy }}
        {% csrf_token %}
        <button type="submit" class='btn btn-block btn-default'><strong>Set new password.</strong></button>
      </form>
    </div>
  </div>
<br/>

{% endblock %}

pysimplelife/templates/core/password_reset_done.html
{% extends 'core/base.html' %}
{% load crispy_forms_filters %}

{% block title %}Reset Password - Pysimplelife{% endblock title %}

{% block content %}

<h2 class='text-align-center'><strong>Reset password</strong></h2>
<div class="panel-body">
    <h3>We've sent an email to the address you specified with instructions for setting a new password.</h3>
    <h3>If you do not receive the email, please check your spam folder. For further assistance please email us at <a href="mailto:patientenportal@v-a-l.nl">pyprogrammer@gmail.com</a>.</h3>
</div>

{% endblock content %}


pysimplelife/templates/core/password_reset_email.html
You are receiving this email because you use the "Forgot Password" feature Pysimplelife. With
link below, you can set a new password:

https://127.0.0.1:8000{% url 'core:password_reset_confirm' uidb64=uid token=token %}

Regards,

Pyprogrammer.com